// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VeiraMal.API;

#nullable disable

namespace VeiraMal.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260319162420_RemoveBatch")]
    partial class RemoveBatch
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VeiraMal.API.Models.AccessLevel", b =>
                {
                    b.Property<int>("AccessLevelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccessLevelId"));

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AccessLevelId");

                    b.ToTable("AccessLevels", "dbo");
                });

            modelBuilder.Entity("VeiraMal.API.Models.AnalysisHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("HeadcountData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsFinal")
                        .HasColumnType("bit");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<string>("NHTData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TermsData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("AnalysisHistory");
                });

            modelBuilder.Entity("VeiraMal.API.Models.BaseRate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RateUnit")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("BaseRates");
                });

            modelBuilder.Entity("VeiraMal.API.Models.BusinessUnit", b =>
                {
                    b.Property<int>("BusinessUnitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BusinessUnitId"));

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BusinessUnitId");

                    b.ToTable("BusinessUnits", "dbo");
                });

            modelBuilder.Entity("VeiraMal.API.Models.Company", b =>
                {
                    b.Property<Guid>("CompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CompanyABN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ParentCompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CompanyId");

                    b.HasIndex("ParentCompanyId");

                    b.ToTable("Companies", "dbo");
                });

            modelBuilder.Entity("VeiraMal.API.Models.CompanySubscription", b =>
                {
                    b.Property<Guid>("CompanySubscriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AdditionalSeatPriceSnapshot")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("AdditionalSeatsPurchased")
                        .HasColumnType("int");

                    b.Property<int>("BaseUserSeatsSnapshot")
                        .HasColumnType("int");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("bit");

                    b.Property<decimal>("MonthlyPriceSnapshot")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PlanNameSnapshot")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SubscriptionPlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TempPasswordProtected")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CompanySubscriptionId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("SubscriptionPlanId");

                    b.ToTable("CompanySubscriptions", "dbo");
                });

            modelBuilder.Entity("VeiraMal.API.Models.CompanySuperUserAssignment", b =>
                {
                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("CompanyId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("CompanySuperUserAssignments", "dbo");
                });

            modelBuilder.Entity("VeiraMal.API.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BaseSalary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BusinessUnit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("FTE")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("HoursPerWeek")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Level")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ManagerEmployeeId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrgUnit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PositionTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SuperPercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalRemuneration")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("VeiraMal.API.Models.EmployeeLiability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BalanceDays")
                        .HasColumnType("int");

                    b.Property<decimal>("BenefitAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("BenefitDays")
                        .HasColumnType("int");

                    b.Property<DateTime>("CalculationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DailyRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("DaysLeftToTake")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("EntitlementDays")
                        .HasColumnType("int");

                    b.Property<decimal>("FutureLeaveBookedDays")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LiabilityAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SourceUploadBatchId")
                        .HasColumnType("int");

                    b.Property<int>("TargetDays")
                        .HasColumnType("int");

                    b.Property<int>("TotalLeaveBalance")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("EmployeeLiabilities");
                });

            modelBuilder.Entity("VeiraMal.API.Models.Headcount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AgeOfEmployee")
                        .HasColumnType("int");

                    b.Property<string>("BusinessUnit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CostCentreDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CostCentreNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmployeeGroup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeSubgroup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmploymentPercentage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GenderKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Month")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameOfSuperior")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrganizationalKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrganizationalUnit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonnelArea")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PersonnelNumber")
                        .HasColumnType("int");

                    b.Property<string>("PersonnelSubarea")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PositionNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PositionTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SalariedOrWaged")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tenure")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WeeklyHours")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Headcounts", (string)null);
                });

            modelBuilder.Entity("VeiraMal.API.Models.LeaveBalance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ALBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("ALNextAnniversary")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("EmployeeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Function")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoundedBalanceDays")
                        .HasColumnType("int");

                    b.Property<int>("UploadBatchId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UploadBatchId");

                    b.ToTable("LeaveBalances");
                });

            modelBuilder.Entity("VeiraMal.API.Models.LeaveTaken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AttendanceAbsenceType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BusinessUnit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ChangedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("CostCentreDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CostCentreNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Days")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("EmploymentPercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("EmploymentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Function")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Hours")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Manager")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Month")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrganizationalUnit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonnelArea")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonnelName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PersonnelNumber")
                        .HasColumnType("int");

                    b.Property<string>("PersonnelSubarea")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UploadBatchId")
                        .HasColumnType("int");

                    b.Property<decimal>("WeeklyHours")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("UploadBatchId");

                    b.ToTable("LeaveTakens");
                });

            modelBuilder.Entity("VeiraMal.API.Models.NHT", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AgeOfEmployee")
                        .HasColumnType("int");

                    b.Property<string>("BusinessUnit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CostCentreDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CostCentreNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmployeeGroup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeSubgroup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmploymentPercentage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GenderKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Month")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameOfSuperior")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrganizationalKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrganizationalUnit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonnelArea")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PersonnelNumber")
                        .HasColumnType("int");

                    b.Property<string>("PersonnelSubarea")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PositionNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PositionTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SalariedOrWaged")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("NHTs", (string)null);
                });

            modelBuilder.Entity("VeiraMal.API.Models.RevokedToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Jti")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RevokedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("RevokedTokens");
                });

            modelBuilder.Entity("VeiraMal.API.Models.SubscriptionPlan", b =>
                {
                    b.Property<Guid>("SubscriptionPlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("AdditionalSeatPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("AdditionalSeatsAllowed")
                        .HasColumnType("bit");

                    b.Property<int>("BaseUserSeats")
                        .HasColumnType("int");

                    b.Property<bool>("HasApi")
                        .HasColumnType("bit");

                    b.Property<string>("IdealFor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KeyFeatures")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MaxHC")
                        .HasColumnType("int");

                    b.Property<string>("Package")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("PricePerMonth")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ReportingLevel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SuperUsers")
                        .HasColumnType("int");

                    b.HasKey("SubscriptionPlanId");

                    b.ToTable("SubscriptionPlans", "dbo");

                    b.HasData(
                        new
                        {
                            SubscriptionPlanId = new Guid("11111111-1111-1111-1111-111111111111"),
                            AdditionalSeatPrice = 0m,
                            AdditionalSeatsAllowed = false,
                            BaseUserSeats = 1,
                            HasApi = false,
                            IdealFor = "Overview",
                            KeyFeatures = "Can explore by seeing dummy reports etc",
                            MaxHC = 50,
                            Package = "Demo",
                            PricePerMonth = 0m,
                            ReportingLevel = "Overview",
                            SuperUsers = 0
                        },
                        new
                        {
                            SubscriptionPlanId = new Guid("22222222-2222-2222-2222-222222222222"),
                            AdditionalSeatPrice = 100m,
                            AdditionalSeatsAllowed = true,
                            BaseUserSeats = 10,
                            HasApi = false,
                            IdealFor = "Startups or small teams that want to self-serve",
                            KeyFeatures = "Basic Reports; Automated onboarding; Report upload",
                            MaxHC = 200,
                            Package = "Starter",
                            PricePerMonth = 1000m,
                            ReportingLevel = "Basic",
                            SuperUsers = 1
                        },
                        new
                        {
                            SubscriptionPlanId = new Guid("33333333-3333-3333-3333-333333333333"),
                            AdditionalSeatPrice = 90m,
                            AdditionalSeatsAllowed = true,
                            BaseUserSeats = 20,
                            HasApi = false,
                            IdealFor = "Growing SMEs needing more capacity",
                            KeyFeatures = "Everything in Starter; Advanced reporting; Dedicated account manager; Optional addons",
                            MaxHC = 400,
                            Package = "Business",
                            PricePerMonth = 2500m,
                            ReportingLevel = "Advanced",
                            SuperUsers = 2
                        },
                        new
                        {
                            SubscriptionPlanId = new Guid("44444444-4444-4444-4444-444444444444"),
                            AdditionalSeatPrice = 0m,
                            AdditionalSeatsAllowed = false,
                            BaseUserSeats = 0,
                            HasApi = false,
                            IdealFor = "Large organisations with complex requirements",
                            KeyFeatures = "4 Superusers; Premium support (Non-Tech); Custom contract and SLA; Dedicated account manager; Custom onboarding support; Unlimited seats; Unlimited HC",
                            Package = "Enterprise",
                            PricePerMonth = 3500m,
                            ReportingLevel = "Advanced",
                            SuperUsers = 4
                        },
                        new
                        {
                            SubscriptionPlanId = new Guid("55555555-5555-5555-5555-555555555555"),
                            AdditionalSeatPrice = 0m,
                            AdditionalSeatsAllowed = false,
                            BaseUserSeats = 0,
                            HasApi = true,
                            IdealFor = "Large organisations with complex requirements",
                            KeyFeatures = "6 Superusers; Premium support; Custom contract and SLA; Dedicated account manager; Premium Reports; Custom onboarding support; Unlimited seats; APIs",
                            Package = "Enterprise Plus",
                            ReportingLevel = "Premium",
                            SuperUsers = 6
                        });
                });

            modelBuilder.Entity("VeiraMal.API.Models.SuperAdmin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PasswordChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SuperAdmins");
                });

            modelBuilder.Entity("VeiraMal.API.Models.Terms", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ActionType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AgeOfEmployee")
                        .HasColumnType("int");

                    b.Property<string>("BusinessUnit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CostCentreDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CostCentreNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmployeeGroup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeSubgroup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmploymentPercentage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GenderKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GradeGrouping")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Manager")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Month")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrganizationalKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrganizationalUnit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonnelArea")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PersonnelNumber")
                        .HasColumnType("int");

                    b.Property<string>("PersonnelSubarea")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReasonForAction")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SalariedOrWaged")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDateAction")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Terms", (string)null);
                });

            modelBuilder.Entity("VeiraMal.API.Models.UploadBatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FilesMeta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UploadedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UploadBatches");
                });

            modelBuilder.Entity("VeiraMal.API.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("AccessLevel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BusinessUnit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContactNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmployeeNumber")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFirstLogin")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPasswordResetRequired")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfilePictureUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserGuid")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId");

                    b.ToTable("Users", "dbo");
                });

            modelBuilder.Entity("VeiraMal.API.Models.Company", b =>
                {
                    b.HasOne("VeiraMal.API.Models.Company", "ParentCompany")
                        .WithMany("ChildCompanies")
                        .HasForeignKey("ParentCompanyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentCompany");
                });

            modelBuilder.Entity("VeiraMal.API.Models.CompanySubscription", b =>
                {
                    b.HasOne("VeiraMal.API.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VeiraMal.API.Models.SubscriptionPlan", "SubscriptionPlan")
                        .WithMany()
                        .HasForeignKey("SubscriptionPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("SubscriptionPlan");
                });

            modelBuilder.Entity("VeiraMal.API.Models.CompanySuperUserAssignment", b =>
                {
                    b.HasOne("VeiraMal.API.Models.Company", "Company")
                        .WithMany("AssignedSuperUsers")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VeiraMal.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VeiraMal.API.Models.LeaveBalance", b =>
                {
                    b.HasOne("VeiraMal.API.Models.UploadBatch", "UploadBatch")
                        .WithMany()
                        .HasForeignKey("UploadBatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UploadBatch");
                });

            modelBuilder.Entity("VeiraMal.API.Models.LeaveTaken", b =>
                {
                    b.HasOne("VeiraMal.API.Models.UploadBatch", "UploadBatch")
                        .WithMany()
                        .HasForeignKey("UploadBatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UploadBatch");
                });

            modelBuilder.Entity("VeiraMal.API.Models.Company", b =>
                {
                    b.Navigation("AssignedSuperUsers");

                    b.Navigation("ChildCompanies");
                });
#pragma warning restore 612, 618
        }
    }
}
